apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: grafana-loki
resources:
- statefulset.yaml
- service.yaml

configMapGenerator:
- name: grafana-loki-config
  files:
  - config/loki-config.yaml