server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"
positions:
  filename: /tmp/positions.yaml
clients: # Specify target
  - url: http://grafana-loki.grafana-loki:3100/loki/api/v1/push
scrape_configs:
  - job_name:  "counter-app" 
    static_configs: 
      - targets: 
          - localhost 
        labels:
          app: "counter-app"
          environment: "dev" 
          __path__: /var/log/*.log # Any file .log in the EmptyDir Volume.